/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Palawan interconnect IDs
 *
 * Copyright (c) 2023, Qualcomm Innovation Center, Inc. All rights reserved.
 * Copyright (c) 2025, Alexandr Zubtsov <internal.hellhound@mainlining.org>
 */

#ifndef __DRIVERS_INTERCONNECT_QCOM_PALAWAN_H
#define __DRIVERS_INTERCONNECT_QCOM_PALAWAN_H

#define PALAWAN_MASTER_A1NOC_SNOC		0
#define PALAWAN_MASTER_A2NOC_SNOC		1
#define PALAWAN_MASTER_ANOC_PCIE_GEM_NOC		2
#define PALAWAN_MASTER_APPSS_PROC		3
#define PALAWAN_MASTER_APSS_NOC			4
#define PALAWAN_MASTER_CAMNOC_HF			5
#define PALAWAN_MASTER_CAMNOC_ICP		6
#define PALAWAN_MASTER_CAMNOC_SF			7                       
#define PALAWAN_MASTER_CDSP_HCP			8
#define PALAWAN_MASTER_CDSP_PROC			9
#define PALAWAN_MASTER_CNOC_CFG			10
#define PALAWAN_MASTER_CNOC_MNOC_HF_CFG 	        11
#define PALAWAN_MASTER_CNOC_MNOC_SF_CFG          12
#define PALAWAN_MASTER_CNOC_SNOC                 13
#define PALAWAN_MASTER_COMPUTE_NOC		14
#define PALAWAN_MASTER_CRYPTO			15
#define PALAWAN_MASTER_GEM_NOC_CNOC		16
#define PALAWAN_MASTER_GEM_NOC_PCIE_SNOC		17
#define PALAWAN_MASTER_GFX3D			18
#define PALAWAN_MASTER_GIC			19
#define PALAWAN_MASTER_GPU_TCU			20
#define PALAWAN_MASTER_IPA			21
#define PALAWAN_MASTER_LLCC			22
#define PALAWAN_MASTER_LPASS_GEM_NOC		23
#define PALAWAN_MASTER_LPASS_LPINOC		24
#define PALAWAN_MASTER_LPASS_PROC		25
#define PALAWAN_MASTER_LPIAON_NOC		26
#define PALAWAN_MASTER_MDP			27
#define PALAWAN_MASTER_MNOC_HF_MEM_NOC		28
#define PALAWAN_MASTER_MNOC_SF_MEM_NOC		29
#define PALAWAN_MASTER_MSS_PROC			30
#define PALAWAN_MASTER_PCIE_0			31
#define PALAWAN_MASTER_PCIE_ANOC_CFG		32
#define PALAWAN_MASTER_QDSS_BAM			33
#define PALAWAN_MASTER_QDSS_ETR			34
#define PALAWAN_MASTER_QDSS_ETR_1		35
#define PALAWAN_MASTER_QSPI_0			36
#define PALAWAN_MASTER_QUP_0			37
#define PALAWAN_MASTER_QUP_1			38
#define PALAWAN_MASTER_QUP_CORE_0		39
#define PALAWAN_MASTER_QUP_CORE_1		40
#define PALAWAN_MASTER_SDCC_2			41
#define PALAWAN_MASTER_SNOC_SF_MEM_NOC		42
#define PALAWAN_MASTER_SYS_TCU			43
#define PALAWAN_MASTER_UFS_MEM			44
#define PALAWAN_MASTER_USB3_0			45
#define PALAWAN_MASTER_VIDEO			46
#define PALAWAN_MASTER_VIDEO_CV_PROC		47
#define PALAWAN_MASTER_VIDEO_PROC		48
#define PALAWAN_MASTER_VIDEO_V_PROC		49
#define PALAWAN_MASTER_WLAN_Q6                   50
#define PALAWAN_SLAVE_A1NOC_SNOC			51
#define PALAWAN_SLAVE_A2NOC_SNOC			52
#define PALAWAN_SLAVE_AHB2PHY_NORTH		53
#define PALAWAN_SLAVE_AHB2PHY_SOUTH		54
#define PALAWAN_SLAVE_ANOC_PCIE_GEM_NOC		55
#define PALAWAN_SLAVE_AOSS			56
#define PALAWAN_SLAVE_APPSS			57
#define PALAWAN_SLAVE_CAMERA_CFG			58
#define PALAWAN_SLAVE_CDSP_MEM_NOC		59
#define PALAWAN_SLAVE_CLK_CTL			60
#define PALAWAN_SLAVE_CNOC_CFG			61
#define PALAWAN_SLAVE_CNOC_MNOC_HF_CFG           62
#define PALAWAN_SLAVE_CNOC_MNOC_SF_CFG           63
#define PALAWAN_SLAVE_CNOC_MSS			64
#define PALAWAN_SLAVE_CPR_NSPCX			65
#define PALAWAN_SLAVE_CRYPTO_0_CFG		66
#define PALAWAN_SLAVE_CX_RDPM			67
#define PALAWAN_SLAVE_DDRSS_CFG			68
#define PALAWAN_SLAVE_DISPLAY_CFG		69
#define PALAWAN_SLAVE_EBI1			70
#define PALAWAN_SLAVE_GEM_NOC_CNOC		71
#define PALAWAN_SLAVE_GFX3D_CFG			72
#define PALAWAN_SLAVE_I3C_IBI0_CFG		73
#define PALAWAN_SLAVE_I3C_IBI1_CFG		74
#define PALAWAN_SLAVE_IMEM			75
#define PALAWAN_SLAVE_IMEM_CFG			76
#define PALAWAN_SLAVE_IPA_CFG			77
#define PALAWAN_SLAVE_IPC_ROUTER_CFG		78
#define PALAWAN_SLAVE_LLCC			79
#define PALAWAN_SLAVE_LPASS_GEM_NOC		80
#define PALAWAN_SLAVE_LPIAON_NOC_LPASS_AG_NOC	81
#define PALAWAN_SLAVE_LPICX_NOC_LPIAON_NOC	82
#define PALAWAN_SLAVE_MEM_NOC_PCIE_SNOC		83
#define PALAWAN_SLAVE_MNOC_HF_MEM_NOC		84
#define PALAWAN_SLAVE_MNOC_SF_MEM_NOC		85
#define PALAWAN_SLAVE_MX_2_RDPM			86
#define PALAWAN_SLAVE_MX_RDPM			87
#define PALAWAN_SLAVE_NSP_QTB_CFG		88
#define PALAWAN_SLAVE_PCIE_0			89
#define PALAWAN_SLAVE_PCIE_0_CFG			90
#define PALAWAN_SLAVE_PCIE_ANOC_CFG		91
#define PALAWAN_SLAVE_PCIE_RSCC			92
#define PALAWAN_SLAVE_PDM			93
#define PALAWAN_SLAVE_PRNG			94
#define PALAWAN_SLAVE_QDSS_CFG			95
#define PALAWAN_SLAVE_QDSS_STM			96
#define PALAWAN_SLAVE_QSPI_0			97
#define PALAWAN_SLAVE_QUP_0			98
#define PALAWAN_SLAVE_QUP_1			99
#define PALAWAN_SLAVE_QUP_CORE_0			100
#define PALAWAN_SLAVE_QUP_CORE_1			101
#define PALAWAN_SLAVE_RBCPR_CX_CFG		102
#define PALAWAN_SLAVE_RBCPR_MMCX_CFG		103
#define PALAWAN_SLAVE_RBCPR_MXC_CFG		104
#define PALAWAN_SLAVE_SDCC_2			105
#define PALAWAN_SLAVE_SERVICE_CNOC		106
#define PALAWAN_SLAVE_SERVICE_CNOC_CFG		107
#define PALAWAN_SLAVE_SERVICE_MNOC_HF            108
#define PALAWAN_SLAVE_SERVICE_MNOC_SF            109
#define PALAWAN_SLAVE_SERVICE_PCIE_ANOC		110
#define PALAWAN_SLAVE_SNOC_GEM_NOC_SF		111
#define PALAWAN_SLAVE_TCSR			112
#define PALAWAN_SLAVE_TCU			113
#define PALAWAN_SLAVE_TLMM			114
#define PALAWAN_SLAVE_TME_CFG			115
#define PALAWAN_SLAVE_UFS_MEM_CFG		116
#define PALAWAN_SLAVE_USB3_0			117
#define PALAWAN_SLAVE_VENUS_CFG			118
#define PALAWAN_SLAVE_VSENSE_CTRL_CFG		119
#define PALAWAN_SLAVE_WLAN                       120
#define PALAWAN_SLAVE_WLAN_Q6_THROTTLE_CFG       121

#endif
